/**
 * Integration test that proves the single most important Phase 2 invariant:
 *
 *   An argon2id hash generated by Python's pwdlib (and sitting in the live
 *   Postgres `users.password_hash` column) can be verified byte-for-byte by
 *   Nest's `AuthService.verifyPassword()` using the `argon2` npm package.
 *
 * If this test fails, the NestJS backend cannot authenticate existing users
 * and the whole port is BLOCKED. It's deliberately wired to the real DB —
 * skipping it in CI would defeat the purpose. The test falls back to a clean
 * "skip with reason" if the DB env isn't set (for contributors without the
 * ts-pg-proxy socat container running locally).
 */
import { ConfigModule, ConfigService } from '@nestjs/config';
import { JwtModule } from '@nestjs/jwt';
import { Test, TestingModule } from '@nestjs/testing';
import { AuthService } from '../src/auth/auth.service';
import { PrismaService } from '../src/prisma/prisma.service';

const hasDb = Boolean(process.env.DATABASE_URL_PRISMA || process.env.DATABASE_URL);
const hasCreds = Boolean(process.env.USER_LOGIN && process.env.USER_PASSWORD);
const maybeDescribe = hasDb && hasCreds ? describe : describe.skip;

maybeDescribe('argon2 portability (real DB)', () => {
  let moduleRef: TestingModule;
  let authService: AuthService;
  let prisma: PrismaService;

  beforeAll(async () => {
    moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({ isGlobal: true, envFilePath: ['../.env', '.env'] }),
        JwtModule.registerAsync({
          imports: [ConfigModule],
          inject: [ConfigService],
          useFactory: (cfg: ConfigService) => ({
            // Fall back to a throw-away secret for the JWT module — we don't
            // actually exercise token signing in this test, but AuthService
            // constructor requires JwtService to be provided.
            secret: cfg.get<string>('SECRET_KEY') ?? 'portability-test-secret',
            signOptions: { algorithm: 'HS256' },
          }),
        }),
      ],
      providers: [AuthService, PrismaService],
    }).compile();

    authService = moduleRef.get(AuthService);
    prisma = moduleRef.get(PrismaService);
    await prisma.$connect();
  });

  afterAll(async () => {
    await prisma?.$disconnect();
    await moduleRef?.close();
  });

  it('verifies the admin user hash against USER_PASSWORD', async () => {
    const login = process.env.USER_LOGIN!;
    const password = process.env.USER_PASSWORD!;

    const admin = await prisma.user.findUnique({ where: { username: login } });
    expect(admin).not.toBeNull();
    if (!admin) return;

    // The hash must have been produced by Python's pwdlib (or our own code,
    // which emits the same format). Either way, argon2.verify should read
    // the params from the string and succeed.
    expect(admin.password_hash).toMatch(/^\$argon2id\$v=19\$m=\d+,t=\d+,p=\d+\$/);

    const matched = await authService.verifyPassword(password, admin.password_hash);
    expect(matched).toBe(true);

    // Negative case: flipping one character must fail.
    const wrongOk = await authService.verifyPassword(password + 'X', admin.password_hash);
    expect(wrongOk).toBe(false);
  });
});
